### PR TITLE
fix: Unhandled promise rejection on registry

### LINKED ISSUE #458: [BUG]: Unhandled promise rejection
Hi,

After #454 I'm facing this problem after a while using the keyboard:

```
Apr 08 20:45:43 SecHackLabs gnome-shell[442208]: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
                                                 _promisify/proto[asyncFunc]@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:448:16
                                                 fromJSON/contentType<@file:///home/edu4rdshl/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/registry.js:231:77
                                                 fromJSON@file:///home/edu4rdshl/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/registry.js:231:39
                                                 read/</</</entriesPromises<@file:///home/edu4rdshl/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/registry.js:95:59
                                                 read/</</<@file:///home/edu4rdshl/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/registry.js:93:62
                                                 @resource:///org/gnome/shell/ui/init.js:21:20
Apr 08 20:45:43 SecHackLabs gnome-shell[442208]: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
                                                 _promisify/proto[asyncFunc]@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:448:16
                                                 fromJSON/contentType<@file:///home/edu4rdshl/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/registry.js:231:77
                                                 fromJSON@file:///home/edu4rdshl/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/registry.js:231:39
                                                 read/</</</entriesPromises<@file:///home/edu4rdshl/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/registry.js:95:59
                                                 read/</</<@file:///home/edu4rdshl/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/registry.js:93:62
                                                 @resource:///org/gnome/shell/ui/init.js:21:20
Apr 08 20:45:43 SecHackLabs gnome-shell[442208]: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
                                                 _promisify/proto[asyncFunc]@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:448:16
                                                 fromJSON/contentType<@file:///home/edu4rdshl/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/registry.js:231:77
                                                 fromJSON@file:///home/edu4rdshl/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/registry.js:231:39
                                                 read/</</</entriesPromises<@file:///home/edu4rdshl/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/registry.js:95:59
                                                 read/</</<@file:///home/edu4rdshl/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/registry.js:93:62
                                                 @resource:///org/gnome/shell/ui/init.js:21:20
Apr 08 20:45:43 SecHackLabs gnome-shell[442208]: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
                                                 _promisify/proto[asyncFunc]@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:448:16
                                                 fromJSON/contentType<@file:///home/edu4rdshl/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/registry.js:231:77
                                                 fromJSON@file:///home/edu4rdshl/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/registry.js:231:39
                                                 read/</</</entriesPromises<@file:///home/edu4rdshl/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/registry.js:95:59
                                                 read/</</<@file:///home/edu4rdshl/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/registry.js:93:62
                                                 @resource:///org/gnome/shell/ui/init.js:21:20
Apr 08 20:45:43 SecHackLabs gnome-shell[442208]: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
                                                 _promisify/proto[asyncFunc]@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:448:16
                                                 fromJSON/contentType<@file:///home/edu4rdshl/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/registry.js:231:77
                                                 fromJSON@file:///home/edu4rdshl/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/registry.js:231:39
                                                 read/</</</entriesPromises<@file:///home/edu4rdshl/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/registry.js:95:59
                                                 read/</</<@file:///home/edu4rdshl/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/registry.js:93:62
                                                 @resource:///org/gnome/shell/ui/init.js:21:20
Apr 08 20:45:43 SecHackLabs gnome-shell[442208]: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
                                                 _promisify/proto[asyncFunc]@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:448:16
                                                 fromJSON/contentType<@file:///home/edu4rdshl/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/registry.js:231:77
                                                 fromJSON@file:///home/edu4rdshl/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/registry.js:231:39
                                                 read/</</</entriesPromises<@file:///home/edu4rdshl/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/registry.js:95:59
                                                 read/</</<@file:///home/edu4rdshl/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/registry.js:93:62
                                                 @resource:///org/gnome/shell/ui/init.js:21:20
```
and it stops working as shown in the image:
image

### PR DESCRIPTION
**Pull request by ken-kuro**
Fix #458 and #459

### CODE REVIEW

File: registry.js [hunk 1]
```diff
@@ -228,16 +228,16 @@ export class ClipboardEntry {
...
+                    return fileInfo.get_content_type();
                 } catch (e) {
-                    reject(e);
+                    console.error(e);
                 }
-            }));
+            });
 
-            if (!contentType.startsWith('image/') && !contentType.startsWith('text/')) {
+            if (contentType && !contentType.startsWith('image/') && !contentType.startsWith('text/')) {
```
Comment (Tudmotu) [inline registry.js:240]: In what situations is there no `contentType`?
Also, if there's no content type, will it treat the file as an image? I'm not sure that's what we want, right?

**Comment by Tudmotu** [comment]
Thank you for this PR @ken-kuro.
Are you sure this also fixes #459 ?

File: registry.js (hunk 1 above)
Comment (ken-kuro) [reply registry.js:240]: I see, I was just add it so that the operations like `startsWith` wouldn't throw an error. About the behavior, it would act the same as the old code, but I think that's not what we want, might open another PR to optimize that later

**Comment by ken-kuro** [comment]
When I test on my machine it does fix the issue, and I didn't have to clear my cache

**Comment by rebelinux** [comment]
I installed from @ken-kuro  repo and can confirm the extension work without the need to clear cache. Thanks!

[Screencast from 2024-04-09 14-37-35.webm](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/assets/1002783/7713cfa9-c1c3-4ae8-b298-0014998e92df)

**Comment by Tudmotu** [comment]
@rebelinux thank you for confirming! :pray:

**Comment by Tudmotu** [comment]
Uploaded to e.g.o and approved by the amazing @jrahmatzadeh within 5 mins.

**Comment by jrahmatzadeh** [comment]
@Tudmotu Thanks!
